# Generated by Django 4.1.1 on 2022-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumblympics_app', '0002_race_alter_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
